#adapted from https://github.com/nextcloud/docker

version: '3'

services:
  db:
    container_name: nextcloud-mariadb
    image: yobasystems/alpine-mariadb:armhf
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=[FILL_HERE]
      - MYSQL_PASSWORD=[FILL_HERE]
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    volumes:
      - ./data/mariadb/db:/var/lib/mysql
      - ./data/mariadb/etc:/etc/mysql

  db_backup:
    container_name: nextcloud-mariadb_backup
    build: 
      context: ./build-mariadb-backup
      args:
        - CRON_CMD=0 5 * * *
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - DB_BACKUP_HOST=nextcloud-mariadb
      - DB_BACKUP_PASSWORD=[FILL_HERE]
      - DB_BACKUP_NAME=nextcloud
    volumes:
      - ./data/mariadb_backup:/backup

  redis:
    image: redis
    container_name: nextcloud-redis
    command: ["redis-server"]
    hostname: nextcloud-redis
    volumes:
      - ./data/redis:/data

  app:
    container_name: nextcloud-app
    image: nextcloud
    depends_on:
      - db
      - redis
    restart: unless-stopped
    ports:
      - "9080:80"
      - "9443:443"
    environment:
      - REDIS_HOST=nextcloud-redis
      - REDIS_PORT=6379
    volumes:
      - ./data/apps:/var/www/html/apps
      - ./data/custom_apps:/var/www/html/custom_apps
      - ./data/config:/var/www/html/config
      - ./data/data:/var/www/html/data
      - ./data/php:/usr/local/etc/php
      - ./data/apache2:/etc/apache2
