#adapted from https://github.com/nextcloud/docker

version: '3'

services:
  db:
    container_name: nextcloud-mariadb
    image: yobasystems/alpine-mariadb:armhf
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=[FILL_HERE]
      - MYSQL_PASSWORD=[FILL_HERE]
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    volumes:
      - ./data/mariadb/db:/var/lib/mysql
      - ./data/mariadb/etc:/etc/mysql

  db_backup:
    container_name: nextcloud-mariadb_backup
    build: 
      context: ./build-mariadb-backup
      args:
        - CRON_CMD=0 5 * * *
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - DB_BACKUP_HOST=nextcloud-mariadb
      - DB_BACKUP_PASSWORD=[FILL_HERE]
      - DB_BACKUP_NAME=nextcloud
    volumes:
      - ./data/mariadb_backup:/backup

  redis:
    image: redis
    container_name: nextcloud-redis
    command: ["redis-server"]
    hostname: nextcloud-redis
    volumes:
      - ./data/redis:/data

  app:
    container_name: nextcloud-app
    image: nextcloud
    depends_on:
      - db
      - redis
    restart: unless-stopped
    ports:
      - "9080:80"
      - "9443:443"
    environment:
      - REDIS_HOST=nextcloud-redis
      - REDIS_PORT=6379
    volumes:
      - ./data/app/apps:/var/www/html/apps
      - ./data/app/custom_apps:/var/www/html/custom_apps
      - ./data/app/config:/var/www/html/config
      - ./data/app/data:/var/www/html/data
      - ./data/app/php.ini:/usr/local/etc/php/php.ini

#Service unable for now :(
#https://github.com/nextcloud/news-updater
#  news-updater:
#    container_name: nextcloud-news_updater
#    build: ./build_updater
#    depends_on:
#      - app
#    restart: unless-stopped
#    environment:
#      - NEWS_PASSWORD=GenerateNewPassword
